### ISSUE TITLE
Extension doesn't load when language mode isn't set correctly

### ISSUE THREAD

**Issue by ahmetskilinc** [zenclabs/reactpreview#26] opened 2021-06-25 14:36 UTC
I am able to install the extension but I am not able to get it to load in my `.jsx` files. It just doesn't show up.

To reproduce, I'm not sure. I just installed it, opened a few projects and it won't recognise the files.

<img width="445" alt="Screenshot 2021-06-25 at 15 35 48" src="https://user-images.githubusercontent.com/37756565/123440843-202f9a00-d5cb-11eb-97ba-65a8cc2ccb37.png">

**Comment by sevenfields-matt** [comment] 2021-06-25 16:29
Found a workaround here:
#11

**Comment by ahmetskilinc** [comment] 2021-06-28 10:46
Has anyone got any updates on this? I'm still not able to use it nor load it.

**Comment by fwouts** [comment] 2021-06-28 10:51
Hey @ahmetskilinc, I'm hoping to get a new release that should hopefully fix this in the next couple of days.

**Comment by ahmetskilinc** [comment] 2021-06-28 10:53
Oh. Nice. Thanks!

**Comment by fwouts** [comment] 2021-06-28 21:49
Hey @ahmetskilinc, v0.2.3 is now out. Would you be able to try it out and confirmed whether that fixed your issue? I'm not 100% sure but hopeful!

**Comment by ahmetskilinc** [comment] 2021-06-28 21:52
<img width="562" alt="Screenshot 2021-06-28 at 22 51 44" src="https://user-images.githubusercontent.com/37756565/123708486-6acb4380-d863-11eb-8593-faefb6d15769.png">

I've just updated it didn't show up, so I removed and installed it again but it still isn't showing up. I can provide some more info if you like.

**Comment by fwouts** [comment] 2021-06-28 21:53
Ah! React Preview cannot work on **.js** files (it's a limitation of [Vite](http://vitejs.dev)). What happens if you rename it to .jsx?

**Comment by ahmetskilinc** [comment] 2021-06-28 21:56
Oh my bad. I was supposed to rename it. I recreated the file but forgot the name.

Okay, so I renamed it and opened it nothing, closed Code and opened it, still nothing.

**Comment by fwouts** [comment] 2021-06-28 22:06
OK, that's strange. Next step, would you be able to run Ctrl/Cmd+Shift+P and choose "Developer: Show logs..." then pick "Extension Host"? If you run a search for `reactpreview`, are there any errors that come up?

**Comment by ahmetskilinc** [comment] 2021-06-28 22:23
<img width="1904" alt="Screenshot 2021-06-28 at 23 22 57" src="https://user-images.githubusercontent.com/37756565/123711088-c8618f00-d867-11eb-8223-fdfbff1fc87d.png">

No results.

**Comment by fwouts** [comment] 2021-06-28 22:32
Thanks for the screenshot!

The "JS" icon next to your jsx files makes me think the problem is that, for some reason, VS Code doesn't consider these files to be React/JSX files. For example I have a React logo icon for jsx files.

I wonder if you have a special configuration?

**Comment by ahmetskilinc** [comment] 2021-06-28 22:36
I've just changed the icon set and it does see it correctly

<img width="341" alt="Screenshot 2021-06-28 at 23 35 58" src="https://user-images.githubusercontent.com/37756565/123712141-a5d07580-d869-11eb-90d9-d09e5d124281.png">

**Comment by ahmetskilinc** [comment] 2021-06-28 22:40
I found the culprit. The "language mode" was set incorrectly, I corrected to default to ReactJavascript and it is now working correctly.

**Comment by fwouts** [comment] 2021-06-28 22:41
Woohoo! 🎉 Do you reckon we should make React Preview work even when that's not the default? It might be possible, although I'm not sure how many other people would be affected by that.

**Comment by ahmetskilinc** [comment] 2021-06-28 22:43
I think one of my old extensions may have changed the setting. It would be useful to either have it as a disclaimer and specify it has to be set, however if it isn't too much work it would be nice to have it work there as well.

**Comment by fwouts** [comment] 2021-07-28 08:13
This should be fixed since v0.3.0 :)

**Closed by fwouts** 2021-07-28 08:13 UTC
Labels: enhancement
