### ISSUE TITLE
tsconfig.json baseUrl not correctly supported

### ISSUE THREAD

**Issue by gunters63** [zenclabs/reactpreview#33] opened 2021-07-01 05:25 UTC
Hi,

The extension looks great, but it seems to have a problem with not recognizing baseUrl in tsconfig.json.

I have all my sources in a src folder and the following line in my tsonfig.json: 
```` "baseUrl": "src",````

This forces me to put the __reactpreview__ folder into the root folder.

I use Tailwind and my wrapper file looks like this:

````
import '../src/css/index.css';

import React from 'react';

export const Wrapper = React.Fragment;
````

The component I want to preview looks like this (somewhere in the src folder):

````
import React from 'react';

type Props = { label?: string; unit?: string };

const Label = ({ label = '', unit = '' }: Props): JSX.Element => {
  return (
    <label
      data-testid="label-text"
      className="truncate bg-red-500 outline-none pointer-events-none">
      <span className="text-xs ">{label}</span>
      {unit && <span className="text-xs">{` (${unit})`}</span>}
    </label>
  );
};

export default Label;

````

Somehow React Preview Server still has problems loading the src/css/index.css file, the extension output looks like this:

````
React Preview Server running at http://localhost:3120.
Unable to load d:/proj/AtlasCopco/EnsoUi/src/css/index.css
````

There definitely is a index.css file at this path :)

Strangely, if a put a copy of my index.css in a css folder in the root (not in src anymore), the preview works,

**Comment by gunters63** [comment] 2021-07-01 05:28
Ah, by the way, maybe it is vite-tsconfig-paths.
My vite.config.ts looks like this:

````
import replace from '@rollup/plugin-replace';
import reactRefresh from '@vitejs/plugin-react-refresh';
import fs from 'fs';
import copy from 'rollup-plugin-copy';
import { defineConfig } from 'vite';
import svgr from 'vite-plugin-svgr';
import tsconfigPaths from 'vite-tsconfig-paths';

const sslOptions = {
  key: fs.readFileSync('certificates/ensobackend.key'),
  cert: fs.readFileSync('certificates/ensobackend.crt'),
};

export default defineConfig({
  plugins: [reactRefresh(), tsconfigPaths(), svgr()],
  build: {
    minify: false,
    chunkSizeWarningLimit: 1000,
    sourcemap: true,
    rollupOptions: {
      plugins: [
        replace({
          preventAssignment: true,
          __buildDate__: () => new Date().toDateString(),
        }),
        copy({
          targets: [
            {
              src: ['./locales'],
              dest: './dist',
            },
          ],
          verbose: true,
          hook: 'writeBundle',
        }),
      ],
    },
  },
  server: {
    https: sslOptions,
  },
  esbuild: {},
});
````

**Comment by gunters63** [comment] 2021-07-01 05:29
[vite-tsconfig-paths](https://github.com/aleclarson/vite-tsconfig-paths) adds support for Typescripts path mapping.

As you are using a custom vite config under the hood, maybe it would make sense to include this plugin by default?

**Comment by fwouts** [comment] 2021-07-01 12:12
Hi @gunters63, thanks for the detailed bug report!

`vite-tsconfig-paths` is included since v0.2.3 already, so this is a bit strange. Maybe it's an issue with the homemade virtual file system plugin.

Would you be able to share a minimal project to reproduce? That way I can add it to the test suite and make sure it never breaks again once fixed :)

By the way, when you say:
> This forces me to put the `__reactpreview__` folder into the root folder.

This sounds like a separate issue, indicating that you'd like to be able to customise where the Wrapper is defined? Or am I misunderstanding?

Thanks 😄

**Comment by gunters63** [comment] 2021-07-01 13:32
Ok, I will try to put something together :)

**Comment by gunters63** [comment] 2021-07-01 13:34
> This sounds like a separate issue, indicating that you'd like to be able to customise where the Wrapper is defined? Or am I misunderstanding?

Hmm I think it would be ok just to use the baseUrl from tsconfig,json so you are not forced to put it outside the base folder.

**Comment by fwouts** [comment] 2021-07-14 13:15
Hi @gunters63, in v0.3.0 (which is being pushed to the VS Code Marketplace as I write this), you can customise the Wrapper location using:
```js
// reactpreview.config.js

module.exports = {
  wrapper: {
    path: 'src/ReactPreviewWrapper.jsx',
    componentName: 'ReactPreviewWrapper',
  }
};
```

Let me know how you go!

**Comment by fwouts** [comment] 2021-08-04 05:15
I'm closing this as it's been fixed for a while now, feel free to reopen if you run into any issues :)

**Closed by fwouts** 2021-08-04 05:15 UTC
Labels: bug, fixed/v0.3.0
